name: Tests

# Trigger on push
on: push

jobs:
  clean-notebook:
    name: Clean Jupyter Notebook
    runs-on: ubuntu-latest

    steps:
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          disable-checks: outputs,execution_count
